In [27]:
import pandas as pd
import numpy as np
import json
import xml.etree.ElementTree as ET

In [28]:
def get_df(file):
    parsed = ET.parse(file)
    root = parsed.getroot()
    
    data = []

    for i, child in enumerate(root):
        data.append(child.attrib)
        
    dfItem = pd.DataFrame.from_records(data).set_index('Id')
    return dfItem

In [31]:
file_directory = '../data'
file = 'Posts.xml'
file_path = file_directory + file

In [32]:
posts = get_df(file_path)

FileNotFoundError: [Errno 2] No such file or directory: '../dataPosts.xml'

In [6]:
users = get_df('Users.xml')

In [7]:
tags = get_df("Tags.xml")

In [8]:
posts.head()

,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditDate,LastActivityDate,...,Tags,AnswerCount,CommentCount,FavoriteCount,ContentLicense,OwnerDisplayName,ParentId,ClosedDate,CommunityOwnedDate,LastEditorDisplayName
Id,,,,,,,,,,,,,,,,,,,,,
1,1,727273,2009-07-15T06:27:46.723,175,114409,<p>A Vista virtual machine I use only has a 10...,1,-1,2020-06-12T13:48:39.473,2018-10-22T12:24:16.070,...,<windows><disk-space><winsxs>,12,10,89,CC BY-SA 3.0,NaN,NaN,NaN,NaN,NaN
24,1,NaN,2009-07-08T16:32:47.817,7,6536,<p>I used to record important technical meetin...,NaN,36744,2012-08-08T21:06:48.087,2020-10-19T16:12:15.757,...,<audio><audio-recording><camtasia>,6,0,5,CC BY-SA 3.0,essamSALAH,NaN,NaN,NaN,NaN
25,2,NaN,2009-07-08T16:34:52.867,0,NaN,<p>You could use a filter on the recording. A ...,9637,1218738,2020-10-09T16:36:16.537,2020-10-09T16:36:16.537,...,NaN,NaN,0,NaN,CC BY-SA 4.0,Burkhard,24,NaN,NaN,NaN
26,2,NaN,2009-07-08T16:59:00.587,0,NaN,"<p>Try out something like Audible for Macs, an...",23242,1218738,2020-10-19T16:12:15.757,2020-10-19T16:12:15.757,...,NaN,NaN,0,NaN,CC BY-SA 4.0,Jas Panesar,24,NaN,NaN,NaN
27,2,NaN,2009-07-08T17:15:59.477,1,NaN,<p>You definitely need some sort of software t...,45675,NaN,NaN,2009-07-15T06:48:44.300,...,NaN,NaN,1,NaN,CC BY-SA 2.5,T Pops,24,NaN,NaN,NaN

In [9]:
relevant = posts[['PostTypeId', 'CreationDate', 'Score', 'Body', 'Tags', 'OwnerUserId', 'AnswerCount', 'ParentId']]
relevant

,PostTypeId,CreationDate,Score,Body,Tags,OwnerUserId,AnswerCount,ParentId
Id,,,,,,,,
1,1,2009-07-15T06:27:46.723,175,<p>A Vista virtual machine I use only has a 10...,<windows><disk-space><winsxs>,1,12,NaN
24,1,2009-07-08T16:32:47.817,7,<p>I used to record important technical meetin...,<audio><audio-recording><camtasia>,NaN,6,NaN
25,2,2009-07-08T16:34:52.867,0,<p>You could use a filter on the recording. A ...,NaN,9637,NaN,24
26,2,2009-07-08T16:59:00.587,0,"<p>Try out something like Audible for Macs, an...",NaN,23242,NaN,24
27,2,2009-07-08T17:15:59.477,1,<p>You definitely need some sort of software t...,NaN,45675,NaN,24
...,...,...,...,...,...,...,...,...
1607673,1,2020-12-06T04:16:34.360,0,<p>I have always created Virtual Machines on m...,<windows><virtualbox><virtual-machine><azure><...,475817,0,NaN
1607675,1,2020-12-06T04:27:04.807,0,"<p><strong>=VLOOKUP(VLOOKUP(A7,InventoryLog,5,...",<microsoft-excel><worksheet-function>,1248251,0,NaN
1607676,2,2020-12-06T04:34:37.490,0,"<p>If you have Python 3 installed, you could u...",NaN,470014,NaN,1315365
1607677,1,2020-12-06T05:11:18.143,0,<p>I have a problem which I cannot figure out....,<windows-10><networking><wifi-configuration><i...,722192,0,NaN
1607678,2,2020-12-06T05:14:36.420,0,"<p>Apparently Above 4G decoding <a href=""https...",NaN,1010837,NaN,1239231

In [10]:
questions = relevant[relevant['PostTypeId'] == '1'].drop(['PostTypeId', 'ParentId'], axis=1)
answers = relevant[relevant['PostTypeId'] == '2'].drop(['PostTypeId', 'AnswerCount', 'Tags'], axis=1)

In [11]:
# Questions only
questions

,CreationDate,Score,Body,Tags,OwnerUserId,AnswerCount
Id,,,,,,
1,2009-07-15T06:27:46.723,175,<p>A Vista virtual machine I use only has a 10...,<windows><disk-space><winsxs>,1,12
24,2009-07-08T16:32:47.817,7,<p>I used to record important technical meetin...,<audio><audio-recording><camtasia>,NaN,6
29,2009-07-15T07:11:46.370,23,<p>What is the difference between the two supe...,<linux><unix><sudo>,13,9
37,2009-07-15T07:17:13.970,4,"<p>My late 2008, Macbook Pro Unibody machine h...",<mac><crash><boot-camp>,26,3
46,2009-07-15T07:20:00.717,16,<p>Is there any way to configure application t...,<windows><boot><windows-vista><uac><elevation>,21,2
...,...,...,...,...,...,...
1607669,2020-12-06T03:17:52.090,0,<p>I'm trying to get the &quot;Facebook Page U...,<facebook><advertisements>,930695,0
1607671,2020-12-06T03:59:14.313,0,"<p>When I start for Windows settings, such as ...",<windows-10><start-menu><windows-search>,1017832,0
1607673,2020-12-06T04:16:34.360,0,<p>I have always created Virtual Machines on m...,<windows><virtualbox><virtual-machine><azure><...,475817,0
1607675,2020-12-06T04:27:04.807,0,"<p><strong>=VLOOKUP(VLOOKUP(A7,InventoryLog,5,...",<microsoft-excel><worksheet-function>,1248251,0
1607677,2020-12-06T05:11:18.143,0,<p>I have a problem which I cannot figure out....,<windows-10><networking><wifi-configuration><i...,722192,0

In [12]:
# Answers only
answers

,CreationDate,Score,Body,OwnerUserId,ParentId
Id,,,,,
25,2009-07-08T16:34:52.867,0,<p>You could use a filter on the recording. A ...,9637,24
26,2009-07-08T16:59:00.587,0,"<p>Try out something like Audible for Macs, an...",23242,24
27,2009-07-08T17:15:59.477,1,<p>You definitely need some sort of software t...,45675,24
34,2009-07-15T07:16:12.363,9,"<p><a href=""http://audacity.sourceforge.net/"" ...",17,24
38,2009-07-15T07:17:21.910,1,<p>On systems where the superuser account is d...,55,29
...,...,...,...,...,...
1607668,2020-12-06T02:59:58.460,0,"<p>These are collapsible styles, you will not ...",1248233,1604060
1607670,2020-12-06T03:17:54.600,0,"<p>As <a href=""https://superuser.com/users/432...",278403,1607663
1607672,2020-12-06T04:10:54.117,0,<p>I've been searching and the problem is &quo...,1240079,1601514
1607676,2020-12-06T04:34:37.490,0,"<p>If you have Python 3 installed, you could u...",470014,1315365
1607678,2020-12-06T05:14:36.420,0,"<p>Apparently Above 4G decoding <a href=""https...",1010837,1239231

In [13]:
# users, don't rerun
users = users.drop_duplicates(subset=['AccountId']).reset_index().set_index('AccountId')

In [14]:
users

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl
AccountId,,,,,,,,,,,,
-1,-1,1,2009-07-12T22:51:42.563,Community,2008-07-31T00:00:00.000,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",79,53210,168298,NaN
1,1,22674,2009-07-12T22:51:42.563,Jeff Atwood,2020-12-03T19:13:49.677,http://www.codinghorror.com/blog/,"El Cerrito, CA","<p><a href=""http://www.codinghorror.com/blog/a...",60396,1706,64,NaN
2,2,363,2009-07-12T22:51:42.563,Geoff Dalgas,2020-11-30T21:21:33.480,http://stackoverflow.com,"Corvallis, OR",<p>Developer on the Stack Overflow team. Find...,337,47,1,https://i.stack.imgur.com/nDllk.png
3,3,101,2009-07-12T22:51:42.563,Jarrod Dixon,2020-11-18T18:24:15.340,http://jarroddixon.com,"Raleigh, NC, United States","<p><a href=""http://blog.stackoverflow.com/2009...",235,533,0,NaN
4,4,1774,2009-07-12T22:51:42.563,Joel Spolsky,2020-10-28T20:04:59.157,https://joelonsoftware.com/,"New York, NY","<p>In 2000 I co-founded Fog Creek Software, wh...",1115,81,8,https://i.stack.imgur.com/C5gBG.jpg?s=128&g=1
...,...,...,...,...,...,...,...,...,...,...,...,...
7571261,1248254,1,2020-12-06T04:40:59.623,user5745279,2020-12-06T04:40:59.623,NaN,NaN,NaN,0,0,0,https://www.gravatar.com/avatar/5e42ec9baa5bb0...
20143310,1248255,1,2020-12-06T04:56:51.923,aussietheatre71,2020-12-06T04:56:51.923,http://db.aussietheatre.com.au,NaN,"<p>in our website you can find <a href=""http:/...",0,0,0,https://www.gravatar.com/avatar/029938f592e3c8...
20143320,1248256,1,2020-12-06T04:59:35.167,Scooba Dooba,2020-12-06T04:59:35.167,NaN,NaN,NaN,0,0,0,https://lh5.googleusercontent.com/-AVVAs47x6q0...
20143339,1248257,1,2020-12-06T05:04:07.383,user1248257,2020-12-06T05:04:07.383,NaN,NaN,NaN,0,0,0,https://www.gravatar.com/avatar/0e6bb707a37d1b...
20143351,1248258,1,2020-12-06T05:07:36.170,saniah akuntansi,2020-12-06T05:07:36.170,NaN,NaN,NaN,0,0,0,https://lh3.googleusercontent.com/a-/AOh14Ghdf...

In [15]:
score = users[['UpVotes', 'DownVotes', 'Reputation', 'Views']].astype(int)
score.describe()

             UpVotes      DownVotes     Reputation          Views
count  957889.000000  957889.000000  957889.000000  957889.000000
mean        3.454732       0.510287      61.691174       6.256935
std        76.751208     181.633768     791.094495     168.099552
min         0.000000       0.000000       1.000000       0.000000
25%         0.000000       0.000000       1.000000       0.000000
50%         0.000000       0.000000       1.000000       0.000000
75%         0.000000       0.000000     101.000000       2.000000
max     53210.000000  168298.000000  338633.000000   63301.000000

In [16]:
score

           UpVotes  DownVotes  Reputation  Views
AccountId
-1           53210     168298           1     79
1             1706         64       22674  60396
2               47          1         363    337
3              533          0         101    235
4               81          8        1774   1115
...            ...        ...         ...    ...
7571261          0          0           1      0
20143310         0          0           1      0
20143320         0          0           1      0
20143339         0          0           1      0
20143351         0          0           1      0

[957889 rows x 4 columns]

Because the up votes and down votes are heavily skew to the top users compared to reputation, it is hard ot determine if to use up votes and down votes are to use reputation, however, we also see that the reputation value is not necessarily related to up votes and down votes and may include views, which may not necessarily mean they are better question answerers. We will likely use either up votes and down votes as a metric of the ability of the user, or use reputation, however, we know we have this data for users, and the most relevant users, those who answer questions likely have this data as well that we can use to help build reviews or identify cold start problems (Where users have no votes or reputation) that we can use a different recommendation system weight to address.

In [17]:
score.UpVotes.value_counts()

0       776650
1        44215
2        27073
3        16409
4        12132
         ...
854          1
1685         1
662          1
2198         1
740          1
Name: UpVotes, Length: 968, dtype: int64

In [18]:
#users.reset_index().set_index('AccountId').loc[users['AccountId'].value_counts()[users['AccountId'].value_counts() > 1].index.tolist()]

KeyError: 'AccountId'

In [19]:
tags

          TagName  Count ExcerptPostId WikiPostId
Id
203      firmware    425        392824     392823
204       upgrade   1183        320795     320794
205    networking  29881        244736     244735
206         audio   6416        257013     257012
207         video   5289        256215     256214
...           ...    ...           ...        ...
20479        gitk      1           NaN        NaN
20480  finereader      1           NaN        NaN
20481       apipa      1       1606069    1606068
20484   xencenter      1           NaN        NaN
20485  google-one      1           NaN        NaN

[5560 rows x 4 columns]

In [20]:
#tags
tags['Count'] = tags['Count'].astype(int)
tag_count = tags[['TagName', 'Count']]
tag_count[tag_count['Count'] > 1].sort_values('Count', ascending=False).shape[0]
print('Total number of tags: ' + str(tag_count.shape[0]))
print('Tags with more than 1 appearance: ' + str(tag_count[tag_count['Count'] > 1].sort_values('Count', ascending=False).shape[0]))
print('Tags with more than 10 appearance: ' + str(tag_count[tag_count['Count'] > 10].sort_values('Count', ascending=False).shape[0]))
print('Tags with more than 50 appearance: ' + str(tag_count[tag_count['Count'] > 50].sort_values('Count', ascending=False).shape[0]))
print('Tags with more than 100 appearance: ' + str(tag_count[tag_count['Count'] > 100].sort_values('Count', ascending=False).shape[0]))
print('Tags with more than 500 appearance: ' + str(tag_count[tag_count['Count'] > 500].sort_values('Count', ascending=False).shape[0]))

Total number of tags: 5560
Tags with more than 1 appearance: 5390
Tags with more than 10 appearance: 4031
Tags with more than 50 appearance: 2088
Tags with more than 100 appearance: 1380
Tags with more than 500 appearance: 414

We can definitely use tags, as there are many tags that appear in the SuperUser database, and many of them that appear a couple of times, and a large amount that appear many times throughout the posts that have appeared on the forum. We can use this tag data to be able to associate different posts with one another and determine users who are best to handle posts of a certain type of category to be able to make better recommendations.

# Validation and Test Data

## New Method

In [ ]:
relevant = posts[['PostTypeId', 'CreationDate', 'Title', 'Body', 'Tags', 'Score', 'OwnerUserId', 'AnswerCount', 'ParentId']]
relevant['CreationDate'] = pd.to_datetime(relevant['CreationDate'])
useful_data = relevant[(relevant['AnswerCount'] != '0') & (relevant['CreationDate'] >= pd.datetime(2018, 1, 1))]
useful_data

In [ ]:
data_q = useful_data[useful_data['PostTypeId'] == '1'].drop(['PostTypeId', 'ParentId', 'AnswerCount', 'Score'], axis=1)
data_a = useful_data[useful_data['PostTypeId'] == '2'].drop(['PostTypeId', 'AnswerCount', 'Tags'], axis=1)

In [ ]:
data_q

In [ ]:
data_a

## Old Method

### Use only needed data and convert to right format

In [21]:
relevant = posts[['PostTypeId', 'CreationDate', 'Score', 'Body', 'Tags', 'OwnerUserId', 'AnswerCount', 'ParentId']]
questions = relevant[relevant['PostTypeId'] == '1'].drop(['PostTypeId', 'ParentId'], axis=1)
answers = relevant[relevant['PostTypeId'] == '2'].drop(['PostTypeId', 'AnswerCount', 'Tags'], axis=1)

In [22]:
relevant['CreationDate'] = pd.to_datetime(relevant['CreationDate'])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
answered_data = relevant[relevant['AnswerCount'] != '0']

###  Split into training and evaluating data

In [24]:
train_data = answered_data[answered_data['CreationDate'] < pd.datetime(2019, 9, 1)]
evaluation_data = answered_data[answered_data['CreationDate'] >= pd.datetime(2019, 9, 1)]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

### Get questions from evaluation data and split in half for validation and testing

In [25]:
question_ids = np.array(evaluation_data[evaluation_data['PostTypeId'] == '1'].index)
np.random.shuffle(question_ids)
valid_questions_index = question_ids[:question_ids.size//2]
test_questions_index = question_ids[question_ids.size//2:]

### Split validation and test datasets into questions and the answers to those questions

In [26]:
valid_questions = evaluation_data.loc[valid_questions_index]
valid_answers = evaluation_data[evaluation_data['ParentId'].isin(valid_questions_index)]

In [27]:
test_questions = evaluation_data.loc[test_questions_index]
test_answers = evaluation_data[evaluation_data['ParentId'].isin(test_questions_index)]

### Split training data, and clean up training, validation, and testing datasets

In [28]:
train_q = train_data[train_data['PostTypeId'] == '1'].drop(['PostTypeId', 'ParentId', 'AnswerCount'], axis=1)
train_a = train_data[train_data['PostTypeId'] == '2'].drop(['PostTypeId', 'AnswerCount', 'Tags'], axis=1)

In [29]:
valid_q  = valid_questions.drop(['CreationDate', 'PostTypeId', 'ParentId', 'AnswerCount'], axis=1)
valid_a = valid_answers.drop(['CreationDate', 'PostTypeId', 'AnswerCount', 'Tags'], axis=1)

In [30]:
test_q = test_questions.drop(['CreationDate', 'PostTypeId', 'ParentId', 'AnswerCount'], axis=1)
test_a = test_answers.drop(['CreationDate', 'PostTypeId', 'AnswerCount', 'Tags'], axis=1)

In [37]:
train_q
train_a

,CreationDate,Score,Body,OwnerUserId,ParentId
Id,,,,,
25,2009-07-08 16:34:52.867,0,<p>You could use a filter on the recording. A ...,9637,24
26,2009-07-08 16:59:00.587,0,"<p>Try out something like Audible for Macs, an...",23242,24
27,2009-07-08 17:15:59.477,1,<p>You definitely need some sort of software t...,45675,24
34,2009-07-15 07:16:12.363,9,"<p><a href=""http://audacity.sourceforge.net/"" ...",17,24
38,2009-07-15 07:17:21.910,1,<p>On systems where the superuser account is d...,55,29
...,...,...,...,...,...
1477618,2019-08-31 22:26:15.427,0,"<p>This may seem sloppy, but you can force the...",1083292,1195310
1477619,2019-08-31 22:35:02.473,1,"<p>If you do <code>man resolv.conf</code>, you...",678518,1475425
1477623,2019-08-31 23:08:20.670,0,<p>There are several things you can try:</p>\n...,NaN,1477435
1477624,2019-08-31 23:48:20.833,3,<p>Both Excel Online and Excel Desktop have th...,NaN,1477620
1478456,2019-08-30 17:37:46.460,4,<p>The <em>jitter</em> command in R usually ta...,NaN,1478455

In [32]:
valid_a

,Score,Body,OwnerUserId,ParentId
Id,,,,
1477639,0,<p>I think I have myself solved my problem try...,1083302,1477630
1477669,14,<p>The <code>/IM</code> parameter for taskkill...,917605,1477654
1477670,5,<p>Create a batch file and use the command Tas...,1067863,1477654
1477707,1,<p>This is how I worked my way around it</p>\n...,297406,1477653
1477713,1,<h3>Let's assume that there is no caching invo...,337631,1477710
...,...,...,...,...
1607655,0,<p>The boot problem is because drive ID's are ...,1248211,1533130
1607656,0,<p>When you try to run <code>rm *.bar</code> a...,432690,1607629
1607665,0,"<p>A few weeks later, I found a <a href=""https...",106758,1602502
1607668,0,"<p>These are collapsible styles, you will not ...",1248233,1604060
1607670,0,"<p>As <a href=""https://superuser.com/users/432...",278403,1607663

In [53]:
test_q.index
#test_a

Index(['1596302', '1549533', '1499764', '1493177', '1556476', '1604892',
       '1579263', '1509013', '1480912', '1536525',
       ...
       '1542283', '1484849', '1572356', '1550781', '1535661', '1592304',
       '1502897', '1516390', '1587559', '1533221'],
      dtype='object', name='Id', length=12682)

In [55]:
valid_a

,Score,Body,OwnerUserId,ParentId
Id,,,,
1477639,0,<p>I think I have myself solved my problem try...,1083302,1477630
1477669,14,<p>The <code>/IM</code> parameter for taskkill...,917605,1477654
1477670,5,<p>Create a batch file and use the command Tas...,1067863,1477654
1477707,1,<p>This is how I worked my way around it</p>\n...,297406,1477653
1477713,1,<h3>Let's assume that there is no caching invo...,337631,1477710
...,...,...,...,...
1607655,0,<p>The boot problem is because drive ID's are ...,1248211,1533130
1607656,0,<p>When you try to run <code>rm *.bar</code> a...,432690,1607629
1607665,0,"<p>A few weeks later, I found a <a href=""https...",106758,1602502
1607668,0,"<p>These are collapsible styles, you will not ...",1248233,1604060
1607670,0,"<p>As <a href=""https://superuser.com/users/432...",278403,1607663

In [35]:
train_q.to_csv('train_q.csv')
valid_q.to_csv('valid_q.csv')
test_q.to_csv('test_q.csv')
train_a.to_csv('train_a.csv')
valid_a.to_csv('valid_a.csv')
test_a.to_csv('test_a.csv')

# Making Test Data

In [1]:
test_file = "../test/testdata.xml"
front = 2
back = 101

In [ ]:
with open(file_path) as myfile:
    head = [next(myfile) for x in range(N)]
    
print(head)

In [ ]:
with open(file_path) as file: 
    tail = []

    # loop to read iterate  
    # last n lines and print it 
    for line in (file.readlines() [-new_N:]): 
        tail.append(line)
        
print(tail)

In [ ]:
f = open("testdata.xml", "a")
f.writelines(head)
f.writelines(tail)
f.close()

# Baseline reccomender

In [49]:
popular = set(list(train_a.OwnerUserId.value_counts().index)[:100])

In [65]:
def baseline(q, a):
    popular = set(list(a.OwnerUserId.value_counts().index)[:100])
    accr = []
    for i in list(q.index):
        answers = set(a[a.ParentId == i].OwnerUserId.values)
        if len(answers.intersection(popular)) > 0:
            accr.append(1)
        else:
            accr.append(0)
    return np.mean(accr)

In [72]:
valid_accr = baseline(valid_q, valid_a)

print('validation accuracy: ', valid_accr)

test_accr = baseline(test_q, test_a)

print('test accuracy: ', test_accr)

validation accuracy:  0.5202271114265437
test accuracy:  0.5082005992745624

In [7]:
import pandas as pd
d = dict()

d['a'] = 1
d['b'] = 2

pd.Series(data = d)

a    1
b    2
dtype: int64

In [74]:
%%time
train_accr = baseline(train_q, train_a)

print('train accuracy: ', train_accr)

train accuracy:  0.2894971124673469
CPU times: user 7h 9min 6s, sys: 3min 14s, total: 7h 12min 21s
Wall time: 7h 12min 19s

In [68]:
train_q.shape

(341468, 5)

In [69]:
train_a.shape

(606450, 5)

In [70]:
valid_a.shape

(16433, 4)

In [71]:
valid_q.shape

(12681, 4)